/**
 * Autogenerated by Thrift Compiler (0.8.0-dev)
 * <p>
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *
 * @generated
 */
package org.pyload.thrift;


public enum Destination implements org.apache.thrift.TEnum {
    Collector(0),
    Queue(1);

    private final int value;

    Destination(int value) {
        this.value = value;
    }

    /**
     * Find a the enum type by its integer value, as defined in the Thrift IDL.
     *
     * @return null if the value is not found.
     */
    public static Destination findByValue(int value) {
        switch (value) {
            case 0:
                return Collector;
            case 1:
                return Queue;
            default:
                return null;
        }
    }

    /**
     * Get the integer value of this enum value, as defined in the Thrift IDL.
     */
    public int getValue() {
        return value;
    }
}
